export const storeConfig = {
  brand: 'NadDigital',
  tagline: 'Des créations numériques pensées pour vous faire avancer.',
  currency: 'USD',
  locale: 'fr-FR',
  whatsapp: '',
  supportEmail: '',
  paymentMethods: [
    {
      id: 'airtel-money',
      label: 'Airtel Money',
      number: 'À configurer',
      accountName: 'À configurer',
    },
    {
      id: 'mpesa',
      label: 'M-Pesa',
      number: 'À configurer',
      accountName: 'À configurer',
    },
  ],
}

export const products = [
  {
    id: 'ebook-ia-poche',
    type: 'ebook',
    title: "L’IA dans ta poche",
    description: 'Un guide pratique pour utiliser l’intelligence artificielle au quotidien, apprendre plus vite et mieux organiser ses projets.',
    price: 5,
    priceIsPlaceholder: true,
    badge: 'E-book',
    icon: 'book',
    featured: true,
  },
  {
    id: 'ebook-prompts-100',
    type: 'ebook',
    title: '100 Prompts IA',
    description: 'Une bibliothèque de prompts classés du niveau basique au niveau avancé pour étudier, créer, travailler et automatiser.',
    price: 4,
    priceIsPlaceholder: true,
    badge: 'E-book',
    icon: 'sparkles',
    featured: true,
  },
  {
    id: 'service-site-web',
    type: 'service',
    title: 'Création de site web',
    description: 'Conception d’un site moderne et responsive pour présenter une activité, une marque, un portfolio ou une boutique.',
    price: 50,
    priceIsPlaceholder: true,
    badge: 'Service',
    icon: 'code',
    featured: true,
  },
  {
    id: 'music-catalogue',
    type: 'music',
    title: 'Créations musicales',
    description: 'Catalogue de créations musicales originales. Les titres, extraits et tarifs définitifs seront ajoutés progressivement.',
    price: 3,
    priceIsPlaceholder: true,
    badge: 'Musique',
    icon: 'music',
    featured: false,
  },
]
